services:
  frontend:
    build: "./frontend/"
    ports: 
      - "3000:5173"
    env_file: 
      - "./frontend/.env"
    volumes: 
      - "./frontend:/app"
      - "/app/node_modules"
  backend:
    build: "./backend/"
    ports: 
      - "3050:8000"
    env_file:
      - "./backend/.env"
    volumes:
      - "./backend:/app"
      - "/app/__pycache__"
